// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string;
export const boxWrapper: string;
export const box: string;
export const info: string;
export const deleteButton: string;
