// This file is automatically generated from your CSS. Any edits will be overwritten.
export const main: string;
export const a: string;
export const b: string;
export const c: string;
export const menuButton: string;
export const mainMenuButton: string;
export const newMain: string;
export const restButtons: string;
