// This file is automatically generated from your CSS. Any edits will be overwritten.
export const imageContainer: string;
export const image: string;
export const imageBox: string;
export const deleteButton: string;
