// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string;
export const main: string;
export const license: string;
export const scrollable: string;
export const bR: string;
export const margin_top_600px: string;
export const marginTop600Px: string;
export const scroll_hide: string;
export const scrollHide: string;
