// This file is automatically generated from your CSS. Any edits will be overwritten.
export const editor: string;
export const generationPanel: string;
export const userPanel: string;
export const resultCentering: string;
export const scaled: string;
