// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const headline: string;
export const icon: string;
export const content: string;
