// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const option: string;
export const caption: string;
export const smallerTextInput: string;
export const editor: string;
export const settingsLine: string;
export const settingsElem: string;
export const settingsElemBig: string;
export const settingsElemMega: string;
export const input: string;
export const radio: string;
