// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const option: string;
export const caption: string;
export const smallerTextInput: string;
