// This file is automatically generated from your CSS. Any edits will be overwritten.
export const scrapper: string;
export const image: string;
export const imageBox: string;
export const chanelBox: string;
